spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/letscook?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: false
  sql:
    init:
      mode: never
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: your-client-id-here
            client-secret: your-secret-here

#mail:
#  host: "localhost"
#  port: 1025
#  username: "letsCook@letsCook.com"
#  password: ""
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BisicBinder: TRACE
